[build]
  publish = "example"
  command = "npm run build && cp -v dist/* example/ && cp -v example/assets/production/* example/ "

[context.production]
  command = "npm run build && cp -v dist/* example/ && cp -v example/assets/production/* example/ "
[context.branch-deploy]
  command = "npm run build && cp -v dist/* example/ && cp -v example/assets/preview/* example/ "
[context.deploy-preview]
  command = "npm run build && cp -v dist/* example/ && cp -v example/assets/preview/* example/ "
